### ISSUE TITLE
RTSP Restreaming is not working

### ISSUE THREAD

**Issue by andrei90** [pedroSG94/AndroidReStreamer#1]
Hello, i changed the VLCReStreamerRtmp with VLCReStreamerRtsp and adapted the main activity.
But i see that the RtspClient never connects to the restreaming url.. and the streaming flag is always false. Could you help me to get this working

**Comment by andrei90** [comment]
I managed to make it work, by connecting in the following method:
  override fun onSpsPpsVpsRtp(sps: ByteBuffer, pps: ByteBuffer, vps: ByteBuffer?) {
    rtspClient.setSPSandPPS(sps, pps, vps)
    if(notConnected) {
      rtspClient.connect();
      notConnected = false;
    }
  }

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/AndroidReStreamer/commit/9bc6557824370d4d6bc2f78f947976200281f1cf
